name: ditto
channels:
  - anaconda
  - nvidia
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - cuda-cudart=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.8.55
  - cuda-runtime=12.4.1
  - cuda-version=12.8
  - filelock=3.13.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - intel-openmp=2023.1.0
  - jinja2=3.1.5
  - ld_impl_linux-64=2.40
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.13.0.11
  - libcurand=10.3.9.55
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=11.2.0
  - libnpp=12.2.5.30
  - libnvfatbin=12.8.55
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - llvm-openmp=14.0.6
  - markupsafe=3.0.2
  - mkl=2023.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpi=1.0
  - mpi4py=3.1.4
  - mpmath=1.3.0
  - ncurses=6.4
  - networkx=3.4.2
  - ocl-icd=2.3.2
  - openmpi=4.0.2
  - openssl=3.0.15
  - pip=25.0
  - python=3.10.16
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - sympy=1.13.3
  - tbb=2021.8.0
  - tk=8.6.14
  - torchtriton=3.1.0
  - typing_extensions=4.12.2
  - tzdata=2025a
  - wheel=0.45.1
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.2.13
