channels:
  - anaconda
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python=3.10
  - pytorch>=2.5,<2.6
  - pytorch-cuda=12.4
  - numpy<2
  - mpi4py>=3,<4
  - openmpi>=4,<5
  - pip
  - pip:
    - packaging>=23
    - tensorrt-cu12==10.7.0
    - tensorrt-cu12-bindings==10.7.0
    - tensorrt-cu12-libs==10.7.0
    - typing-extensions>=4.7.0
    - tensorrt-llm==v0.16.0
