name: ditto
channels:
  - anaconda
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - mpi4py=3.1.4
  - openmpi=4.0.2
  - pip=25.0
  - python=3.10.16
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - setuptools=75.8.0
  - wheel=0.45.1
