#!/usr/bin/env python

import os

from huggingface_hub import snapshot_download
from typer import Typer

app = Typer()


@app.command()
def main(repo_ids: list[str], output_dir: str = "") -> None:
    """Download model snapshots from the HuggingFace Hub."""
    if not output_dir:
        output_dir = "downloads"
    for repo_id in repo_ids:
        repo_output_dir = os.path.join(output_dir, repo_id)
        os.makedirs(repo_output_dir, exist_ok=True)
        result = snapshot_download(repo_id=repo_id, local_dir=repo_output_dir)
        print(f"Downloaded {repo_id} at {result}")


if __name__ == "__main__":
    app()
