from .eliminate_empty_tensors_from_cat_or_stack import eliminate_empty_tensors_from_cat_or_stack
from .eliminate_nop_cat_or_stack import eliminate_nop_cat_or_stack
from .insert_gather_last_token_ids import insert_gather_last_token_ids
from .instantiate_fake_gpt_attention_plugins import instantiate_fake_gpt_attention_plugins
from .populate_fake_gpt_attention_plugin_inputs import populate_fake_gpt_attention_plugin_inputs
from .replace_operator_sub_by_aten_sub import replace_operator_sub_by_aten_sub
from .replace_sdpa_by_fake_gpt_attention_plugin import replace_sdpa_by_fake_gpt_attention_plugin
